__pinocchio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from __pinocchio import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # ''' MAIN '''
    path("", include("main.urls", namespace="main")),
    # ''' Users '''
    path("user/", include("users.urls", namespace="user")),
    # ''' Carts '''
    path("cart/", include("carts.urls", namespace="cart")),
    # ''' Orers '''
    path("orders/", include("orders.urls", namespace="orders")),
    # ''' Manager '''
    path("manager/", include("manager.urls", namespace="manager")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import IndexView

app_name = 'main'

urlpatterns = [
    # ''' MAIN '''
    path("", IndexView.as_view(), name="index"),
]

manager/urls.py
from django.urls import path
from manager import views
from manager.views import (
    ManagerDashboardView,
    ProcessingOrdersView,
    ViewOrderDetailView,
    RemoveOrderView,
    EditOrderView,
    OrderQuantityChangeView,
    OrderRemoveCartView,
    AddOrderItemView,
    ConfirmOrderView,
    ConfirmsOrderListView,
    ReturnProcessingView,
)

app_name = "manager"

urlpatterns = [
    # ''' MANAGER '''
    path("", ManagerDashboardView.as_view(), name="index"),
    path(
        "processing_orders/", ProcessingOrdersView.as_view(), name="processing_orders"
    ),
    path("view_orders/<int:pk>/", ViewOrderDetailView.as_view(), name="view_orders"),
    # Удаление заказа
    path("remove_orders/", RemoveOrderView.as_view(), name="remove_orders"),
    # '''Edit-Order'''
    path("edit_order/<int:pk>/", EditOrderView.as_view(), name="edit_order"),
    path("order_quantity_change/", OrderQuantityChangeView.as_view(), name="order_quantity_change"),
    path("order_remove_cart/", OrderRemoveCartView.as_view(), name="order_remove_cart"),
    path("add_order_item/<int:order_id>/", AddOrderItemView.as_view(), name="add_order_item"),
    path("confirm_order/", ConfirmOrderView.as_view(), name="confirm_order"),
    # '''Confirms-Order'''
    path("confirms_order/", ConfirmsOrderListView.as_view(), name="confirms_order"),
    # '''Возвращаем в обработку'''
   path("return_processing/<int:order_id>/", ReturnProcessingView.as_view(), name="return_processing"),
    # '''Список наших блюд'''
    path("view_products/", views.view_products, name="view_products"),
    # '''Редактирование блюда''
    path("edit_product/<int:product_id>/", views.edit_product, name="edit_product"),
    # '''Добовление блюда в стоплист''
    path("add_to_stop_list/", views.add_to_stop_list, name="add_to_stop_list"),
    # '''Добовление нового блюда''
    path("add_product/", views.add_product, name="add_product"),
]

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from main.models import Products

class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ["name", "description", "image", "price", "discount", "show", "category"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Название продукта"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Описание продукта"}),
            "image": forms.FileInput(attrs={"class": "form-control-file"}),
            "price": forms.NumberInput(attrs={"class": "form-control", "step": "0.01", "placeholder": "Цена"}),
            "discount": forms.NumberInput(attrs={"class": "form-control", "step": "0.01", "placeholder": "Скидка (%)"}),
            "category": forms.Select(attrs={"class": "form-control"}),
        }

manager/views.py
from datetime import datetime
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views import View
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.http import Http404, JsonResponse
from django.db.models import Sum, Count, F
from main.models import Categories, Products
from manager.forms import ProductForm
from orders.models import Order, OrderItem

# from django.views.decorators.http import require_POST

# Группа для прав доступа к странице
def group_required(groups):
    def check_user_group(user):
        return user.groups.filter(name__in=groups).exists() or user.is_superuser

    return user_passes_test(check_user_group)


@method_decorator(group_required(["Manager"]), name="dispatch")
class ManagerDashboardView(TemplateView):
    template_name = "manager/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Total number of orders
        context["total_orders"] = Order.objects.count()

        # Total revenue from orders (sum of prices and quantities for all order items)
        context["total_revenue"] = (
            OrderItem.objects.aggregate(total=Sum(F("price") * F("quantity")))["total"]
            or 0
        )

        # Most popular product based on order item quantity
        popular_product = (
            OrderItem.objects.values("product__name")
            .annotate(total_quantity=Sum("quantity"))
            .order_by("-total_quantity")
            .first()
        )
        context["popular_product_name"] = (
            popular_product["product__name"] if popular_product else "Нет данных"
        )

        # Latest orders (e.g., 10 most recent orders)
        context["latest_orders"] = Order.objects.prefetch_related("orderitem_set").order_by(
            "-created_timestamp"
        )[:10]

        return context

# Список новых заказов
@method_decorator(group_required(["Manager"]), name="dispatch")
class ProcessingOrdersView(ListView):
    model = Order
    template_name = "manager/processing_orders.html"
    context_object_name = "orders"

    def get_queryset(self):
        # Filter orders with the status "В обработке"
        return Order.objects.filter(status="В обработке")

    def get_context_data(self, **kwargs):
        # Add additional context for the count of orders
        context = super().get_context_data(**kwargs)
        context["count_order"] = self.get_queryset().count()
        return context


# Просмотр информации по заказу
@method_decorator(group_required(["Manager"]), name="dispatch")
class ViewOrderDetailView(DetailView):
    model = Order
    template_name = "manager/view_order.html"
    context_object_name = "order"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get related order items
        order_items = OrderItem.objects.filter(order=self.object)

        # Calculate total price and total quantity
        total_price = sum(item.price * item.quantity for item in order_items)
        total_quantity = sum(item.quantity for item in order_items)

        # Determine payment status
        if self.object.payment_on_get:
            status_payment = "Оплата после получения"
        elif self.object.is_paid:
            status_payment = "Заказ оплачен картой"
        else:
            status_payment = "Не оплачено"

        # Add custom context
        context["order_items"] = order_items
        context["total_price"] = total_price
        context["total_quantity"] = total_quantity
        context["status_payment"] = status_payment

        return context


# Удаление существующего заказа
@method_decorator(group_required(["Manager"]), name="dispatch")
class RemoveOrderView(View):
    def post(self, request, *args, **kwargs):
        # Get `order_id` from the request POST data
        order_id = request.POST.get("order_id")

        if not order_id:
            return JsonResponse({"error": "ID заказа не передан."}, status=400)

        # Find the order or return a 404 error
        order = get_object_or_404(Order, id=order_id)
        order.delete()  # Delete the order

        return JsonResponse({"message": "Заказ успешно удалён."})

    def get(self, request, *args, **kwargs):
        return JsonResponse(
            {"error": "Удаление доступно только через POST-запрос."}, status=405
        )


# ''' Редактирование заказа пользователя '''
@method_decorator(group_required(["Manager"]), name="dispatch")
class EditOrderView(DetailView):
    model = Order
    template_name = "manager/edit_order.html"
    context_object_name = "order"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get related order items
        order_items = OrderItem.objects.filter(order=self.object)

        # Calculate total price and total quantity
        total_price = sum(item.price * item.quantity for item in order_items)
        total_quantity = sum(item.quantity for item in order_items)

        # List of all products for modal selection
        products = Products.objects.all()

        # Prepare context data
        context["order_items"] = order_items
        context["total_price"] = total_price
        context["total_quantity"] = total_quantity
        context["products"] = products
        context["added_product_ids"] = [item.product.id for item in order_items]

        return context


# Изменение кол-ва блюд в заказе
@method_decorator(group_required(["Manager"]), name="dispatch")
class OrderQuantityChangeView(View):
    def post(self, request, *args, **kwargs):
        # Get order item ID and new quantity from POST data
        order_id = request.POST.get("order_id")
        quantity = request.POST.get("quantity")

        if not order_id or not quantity:
            return JsonResponse({"error": "order_id и quantity обязательны."}, status=400)

        # Get the specific order item or return 404 if not found
        order_item = get_object_or_404(OrderItem, id=order_id)

        # Update the quantity
        try:
            order_item.quantity = int(quantity)
            order_item.save()
        except ValueError:
            return JsonResponse({"error": "Количество должно быть числом."}, status=400)

        return JsonResponse({"success": True})

# Удаление блюда из заказа пользлвателя
@method_decorator(group_required(["Manager"]), name="dispatch")
class OrderRemoveCartView(View):
    def post(self, request, *args, **kwargs):
        # Get order item ID from POST data
        order_id = request.POST.get("order_id")

        if not order_id:
            return JsonResponse({"error": "ID заказа не передан."}, status=400)

        # Get the order item or return 404
        order_item = get_object_or_404(OrderItem, id=order_id)

        # Delete the order item
        order_item.delete()

        return JsonResponse({"success": True})

    def get(self, request, *args, **kwargs):
        return JsonResponse(
            {"error": "Удаление доступно только через POST-запрос."}, status=405
        )


# Добавление нового товара в заказ пользователя
@method_decorator(group_required(["Manager"]), name="dispatch")
class AddOrderItemView(View):
    def post(self, request, order_id, *args, **kwargs):
        # Retrieve the order using `order_id`
        order = get_object_or_404(Order, pk=order_id)

        # Get product_id and quantity from POST data
        product_id = request.POST.get("product_id")
        quantity = request.POST.get("quantity")

        if not product_id or not quantity:
            # If either value is missing, return an error
            return JsonResponse({"error": "Продукт или количество не переданы."}, status=400)

        try:
            quantity = int(quantity)  # Ensure quantity is a valid integer
        except ValueError:
            return JsonResponse({"error": "Количество должно быть числом."}, status=400)

        # Find the product or return 404 if not found
        product = get_object_or_404(Products, pk=product_id)

        # Create a new order item
        OrderItem.objects.create(
            order=order,
            product=product,
            quantity=quantity,
            name=product.name,  # Save the product's name
            price=product.price,  # Save the product's price
        )

        # Redirect back to the referring page
        return redirect(request.META.get("HTTP_REFERER", "/"))


# Подтверждаем заказ пользователя
@method_decorator(group_required(["Manager"]), name="dispatch")
class ConfirmOrderView(View):
    def post(self, request, *args, **kwargs):
        # Retrieve data from POST request
        order_id = request.POST.get("order_id")
        order_date = request.POST.get("dateOrder")

        # Check if order_date is provided
        if not order_date:
            raise Http404("Страница не найдена")

        # Convert date string to datetime object
        try:
            order_date_obj = datetime.strptime(order_date, "%Y-%m-%dT%H:%M")  # datetime-local format
        except ValueError:
            raise Http404("Страница не найдена")

        # Retrieve the order by ID or raise 404
        order = get_object_or_404(Order, id=order_id)

        # Update order fields
        order.order_date = order_date_obj
        order.status = "Подтвержден"
        order.save()  # Save changes

        # Redirect to processing orders page
        return redirect("manager:processing_orders")

    def get(self, request, *args, **kwargs):
        raise Http404("Страница не найдена")


# Список подтвержденных заказов
@method_decorator(group_required(["Chefs", "Manager"]), name="dispatch")
class ConfirmsOrderListView(ListView):
    model = Order
    template_name = "manager/confirms_order.html"

manager/templates/manager/confirms_order.html
{% extends "manager_base.html" %}
{% load static %}
{% block Title %}Подтвержденные заказы{% endblock  %}
{% block header-title %}
Подтвержденные заказы
<span class="badge badge-success badge-pill ml-3" style="font-size:12px;">
    {{count_order}}
</span>
{% endblock %}

{# Контент на странице #}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% if orders %}<h4 class="card-title">Список новых заказов</h4>{% endif %}
                {% if not orders %}
                
                <h3>Список заказов пуст</h3>
                {% else %}
                <table id="new-orders-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>№ Заказа</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Email</th>
                            <th>Телефон</th>
                            <th>Дата заказа</th>
                            <th>Сумма</th>
                            <th>Действие</th>
                        </tr>
                    </thead>               
                    <tbody>
                        {% for order in orders  %}
                        <tr id="order-row-{{ order.id }}">
                            <td>{{order.id}}</td>
                            <td>{{order.user.first_name}}</td>
                            <td>{{order.user.last_name}}</td>
                            <td>{{order.user.email}}</td>
                            <td>{{order.phone_number}}</td>
                            <td>{{order.created_timestamp|date:"d.m.Y H:i"}}</td>
                            <td>{{order.total_price}} ₽</td>
                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        ....
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="{% url "manager:view_orders" order.id %}">Просмотреть</a>
                                        
                                        <a class="dropdown-item" href="{% url "manager:return_processing" order.id %}">Вернуть в обработку</a>
                                        
                                        <a class="dropdown-item" 
                                           id="order_delete" 
                                           data-order-delete-id={{order.id}}
                                           data-order-delete-url = "{% url "manager:remove_orders"%}"
                                           href="#">
                                           Удалить
                                        </a>
                                        {% csrf_token %}
                                    </div>
                                  </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>
<!-- end row-->
    
{% endblock %}

manager/templates/manager/edit_order.html
{% extends "manager_base.html" %}
{% load static %}
{% block Title %}Редактирование заказа{% endblock  %}
{% block header-title %}Редактирование заказа № {{order.id}}{% endblock %}

{# Контент на странице #}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mt-4">
                        <div class="col-6">
                            <h6 class="font-weight-bold"><strong>Инфо:</strong></h6>

                            <address class="line-h-24">
                                <b>{{order.user.first_name}} {{order.user.last_name}}</b><br>
                                {{order.user.email}}<br>
                                <abbr title="Phone">P:</abbr> {{order.phone_number}}
                            </address>

                        </div><!-- end col -->
                        <div class="col-6">
                            <div class="mt-3 float-right">
                                <p class="mb-2"><strong>Дата заказа: </strong> {{order.created_timestamp|date:"d.m.Y H:i"}}</p>
                                <p class="mb-2"><strong>Статус заказа: </strong> <span class="badge badge-soft-success">{{order.status}}</span></p>
                                <p class="m-b-10"><strong>Order ID: </strong> #{{order.id}}</p>
                            </div>
                        </div><!-- end col -->
                    </div>
                    <!-- end row -->
                                        
                <form method="post" id="orderEditFormID">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table mt-4">
                                    <thead>
                                    <tr><th>№ п/п</th>
                                        <th>Заказанное блюдо</th>
                                        <th>Количество</th>
                                        <th>Цана за ед.</th>
                                        <th class="text-right">Общая цена</th>
                                        <th class="text-right">&nbsp;</th>
                                    </tr></thead>
                                    <tbody>
                                    {% for item in order_items %}   
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>
                                            <input class="form-control form-control-sm" 
                                                   type="text" 
                                                   value="{{item.name}}" readonly>
                                            <br/>
                                            Категория: {{item.product.category.title}}
                                        </td>
                                        <td>
                                            {# Изменение кол-ва заказов #}
                                            <div class="d-flex align-items-center w-100">
                                                <button class="btn btn-outline-secondary btn-sm me-2 znak-products decrement px-md-3" 
                                                        data-order-id="{{ item.id }}"
                                                        data-order-change-url="{% url 'manager:order_quantity_change' %}">
                                                    {% csrf_token %}           
                                                    <i class="mdi mdi-minus"></i>
                                                </button>
                                            
                                                <input type="text" value="{{item.quantity}}" min="1"
                                                       class="form-control form-control-sm text-center fw-bold fs-6 number" 
                                                       style="flex-grow: 1; width: auto;" readonly>
                                            
                                                <button class="btn btn-outline-secondary btn-sm ms-2 znak-products increment px-md-3" 
                                                        data-order-id="{{ item.id }}"
                                                        data-order-change-url="{% url 'manager:order_quantity_change' %}">
                                                    {% csrf_token %}
                                                    <i class="mdi mdi-plus"></i>
                                                </button>
                                            </div>
                                        </td>
                                        <td>{{item.product.sell_price|floatformat:2}} ₽</td>
                                        <td class="text-right">
                                            {{item.products_price|floatformat:2}} ₽
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-danger remove_order_cart"
                                                        data-remove-id="{{ item.id }}"
                                                        data-remove-change-url="{% url 'manager:order_remove_cart' %}"
                                                        >                                                
                                                <span class="mdi mdi-delete"></span>                                               
                                            </button>
                                            {% csrf_token %}
                                        </td>
                                    </tr>
                                    {% endfor %}                                   
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                                <!-- Button trigger modal -->
                                <button type="button" 
                                        class="btn btn-primary btn-sm" 
                                        data-toggle="modal" 
                                        data-target="#AddFoodBtn">
                                        Добавить блюдо
                                </button>
                            <div class="clearfix pt-5">
                                <h6 class="text-uppercase">Общая сумма:</h6>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="float-right">
                                <p><b>Общее количество:</b> {{total_quantity}}</p>
                                <h3>{{total_price|floatformat:2}} ₽</h3>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>

                    <div class="d-print-none my-4">
                        <div class="text-right">
                            <a href="javascript:window.print()" class="btn btn-primary waves-effect waves-light"><i class="fa fa-print m-r-5"></i> Print</a>
                            <a href="{% url "manager:processing_orders" %}" class="btn btn-info waves-effect waves-light">Применить</a>
                        </div>
                    </div>
                </form>
                </div>
            </div> <!-- end card-->
        </div> <!-- end col -->
    </div>
    <!-- end row -->

    <!-- Модальное окно с возможностью выбора блюд -->
  <div class="modal fade" id="AddFoodBtn" tabindex="-1" role="dialog" aria-labelledby="AddFoodBtnTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Добавить новое блюдо</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{% url 'manager:add_order_item' order.id %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="productSelect" class="form-label">Выберите блюдо</label>
                        <select id="productSelect" name="product_id" class="form-select">
                            {% for product in products %}
                                {% if product.id not in added_product_ids %}
                                    <option value="{{ product.id }}">{{ product.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="quantityInput" class="form-label">Количество</label>
                        <input type="number" id="quantityInput" name="quantity" class="form-control" placeholder="Количество" min="1" value="1">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
  </div>
{% comment %} ------------------ {% endcomment %}

{% endblock %}

{% block jsScripts %}
    <!-- Custom Sweetalert2 js File -->
    <script src="{% static "sweetalert2/sweetalert2.min.js" %}"></script>
    <!-- Me Scpript JS Manager -->
    <script src="{% static "manager/js/edit-order.js" %}"></script>
{% endblock %}

manager/templates/manager/processing_orders.html
{% extends "manager_base.html" %}
{% load static %}
{% block Title %}Новые заказы{% endblock  %}
{% block header-title %}
Новые заказы
<span class="badge badge-info badge-pill ml-3" style="font-size:12px;">
    {{count_order}}
</span>
{% endblock %}

{# Контент на странице #}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% if orders %}<h4 class="card-title">Список новых заказов</h4>{% endif %}
                {% if not orders %}
                
                <h3>Список заказов пуст</h3>
                {% else %}
                <table id="new-orders-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>№ Заказа</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Email</th>
                            <th>Телефон</th>
                            <th>Дата заказа</th>
                            <th>Сумма</th>
                            <th>Действие</th>
                        </tr>
                    </thead>               
                    <tbody>
                        {% for order in orders  %}
                        <tr id="order-row-{{ order.id }}">
                            <td>{{order.id}}</td>
                            <td>{{order.user.first_name}}</td>
                            <td>{{order.user.last_name}}</td>
                            <td>{{order.user.email}}</td>
                            <td>{{order.phone_number}}</td>
                            <td>{{order.created_timestamp|date:"d.m.Y H:i"}}</td>
                            <td>{{order.total_price}} ₽</td>
                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        ....
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="{% url "manager:view_orders" order.id %}">Просмотреть</a>
                                        {% if order.payment_on_get %}
                                            <a class="dropdown-item" href="{% url "manager:edit_order" order.id %}">Редактировать</a>
                                        {% endif %}
                                        <a class="dropdown-item" 
                                           id="order_delete" 
                                           data-order-delete-id={{order.id}}
                                           data-order-delete-url = "{% url "manager:remove_orders"%}"
                                           href="#">
                                           Удалить
                                        </a>
                                        {% csrf_token %}
                                    </div>
                                  </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>
<!-- end row-->
    
{% endblock %}

{% block jsScripts %}
    <!-- Custom Sweetalert2 js File -->
    <script src="{% static "sweetalert2/sweetalert2.min.js" %}"></script>
    <!-- Проверка формы на корректность даты -->
    <script src="{% static "manager/js/delete-order.js" %}"></script>
{% endblock %}