__pinocchio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from __pinocchio import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # ''' MAIN '''
    path("", include("main.urls", namespace="main")),
    # ''' Users '''
    path("user/", include("users.urls", namespace="user")),
    # ''' Carts '''
    path("cart/", include("carts.urls", namespace="cart")),
    # ''' Orers '''
    path("orders/", include("orders.urls", namespace="orders")),
    # ''' Manager '''
    path("manager/", include("manager.urls", namespace="manager")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from carts.views import CartAddView, CartChangeView, CartRemoveView

app_name = 'carts'

urlpatterns = [
    # ''' CARTS '''
    path("cart_add/", CartAddView.as_view(), name="cart_add"),
    path("cart_change/", CartChangeView.as_view(), name="cart_change"),
    path("cart_remove/", CartRemoveView.as_view(), name="cart_remove"),
]

main/urls.py
from django.urls import path
from main.views import IndexView

app_name = 'main'

urlpatterns = [
    # ''' MAIN '''
    path("", IndexView.as_view(), name="index"),
]

orders/urls.py
from django.urls import path
from orders.views import CreateOrderView

app_name = "orders"

urlpatterns = [
    # ''' ORDERS '''
    path("create_order/", CreateOrderView.as_view(), name="create_order"),
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users.views import (
    LoginView,
    RegisterView,
    LogoutView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    CheckEmailView,
    CheckUsernameView,
)

app_name = "users"

urlpatterns = [
    # Авторизация, регистрация и выход
    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    
    # Сброс пароля пользователя
    path("password_reset/", PasswordResetRequestView.as_view(), name="password_reset"),
    path(
        "password_reset_done/",
        TemplateView.as_view(template_name="users/resset/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    
    # Проверка username
    path("check_username/", CheckUsernameView.as_view(), name="check_username"),
    # Проверка уникальности email
    path("check_email/", CheckEmailView.as_view(), name="check_email"),
]

carts/models.py
from django.db import models
from django.utils.html import format_html

from main.models import Products
from users.models import User


#  ''' Считаем общее кол-во товаров и их стоимость '''
class CartQuerySet(models.QuerySet):
    # Полная стоимость всех корзин покупателя
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    # Общее кол-во товаров в корзинах
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


# Модель корзины товаров
class Cart(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Пользователь",
    )
    session_key = models.CharField(
        max_length=32, blank=True, null=True, verbose_name="Ключ сессии"
    )
    product = models.ForeignKey(
        to=Products, on_delete=models.CASCADE, verbose_name="Продукт"
    )
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name="Количество")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")

    class Meta:
        db_table = "carts"
        verbose_name = "Корзину"
        verbose_name_plural = "Корзины"

    objects = CartQuerySet().as_manager()

    # Метод для отображения миниатюры в админке
    def image_tag(self):
        if self.product.image:
            return format_html('<img src="{}" style="width: 50px; height: auto;" />', self.product.image.url)
        return "Нет изображения"
    image_tag.short_description = "Миниатюра"

    # Цена общего кол-ва товаров
    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        if self.user:
            return f"Корзина: {self.user.username} | Товар: {self.product.name} | Кол-во: {self.quantity}"
        return f"Анонимная корзина | Товар: {self.product.name} | Кол-во: {self.quantity}"

orders/forms.py
from django import forms


class CreateOrderForm(forms.Form):

    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", "False"),
            ("1", "True"),
        ],
    )

users/forms.py
from pyexpat import model
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm
from django.forms import fields

from users.models import User


# Форма авторизации ===>
class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                "class": "form-control form-control-lg",
                "placeholder": "Имя пользователя",
                "required": True,
                "autocomplete": "off",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": "form-control form-control-lg",
                "placeholder": "Ваш пароль",
                "required": True,
                "autocomplete": "off",
            }
        ),
    )

    class Meta:
        model = User
        fields = ["username", "password"]


# Форма для регистрации пользователя
class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "password1",
            "password2",
        )

    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    phone_number = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

# Форма для восстановления пароля пользователя
class PasswordResetRequestForm(PasswordResetForm):
    
    class Meta:
        model = User
        fields = (            
            "email",            
        )  

    email = forms.EmailField(max_length=100)    

carts/views.py
from django.views import View
from django.http import JsonResponse
from django.template.loader import render_to_string
from carts.models import Cart
from carts.utils import get_user_carts
from main.models import Products



class CartAddView(View):
    """Добавление товара в корзину"""

    def post(self, request, *args, **kwargs):
        product_id = request.POST.get("product_id")
        product = Products.objects.get(id=product_id)

        if request.user.is_authenticated:
            carts = Cart.objects.filter(user=request.user, product=product)
            if carts.exists():
                cart = carts.first()
                cart.quantity += 1
                cart.save()
            else:
                Cart.objects.create(user=request.user, product=product, quantity=1)
        else:
            session_key = request.session.session_key
            if not session_key:
                request.session.create()

            carts = Cart.objects.filter(
                session_key=request.session.session_key, product=product
            )
            if carts.exists():
                cart = carts.first()
                cart.quantity += 1
                cart.save()
            else:
                Cart.objects.create(
                    session_key=request.session.session_key,
                    product=product,
                    quantity=1,
                )

        user_cart = get_user_carts(request)
        cart_items_html = render_to_string(
            "carts/carts.html", {"carts": user_cart}, request=request
        )
        response_data = {
            "message": "Товар добавлен в корзину",
            "cart_items_html": cart_items_html,
        }

        return JsonResponse(response_data)


class CartChangeView(View):
    """Изменение количества товара в корзине"""

    def post(self, request, *args, **kwargs):
        cart_id = request.POST.get("cart_id")
        quantity = request.POST.get("quantity")
        cart = Cart.objects.get(id=cart_id)
        cart.quantity = quantity
        cart.save()

        updated_quantity = cart.quantity
        user_cart = get_user_carts(request)
        cart_items_html = render_to_string(
            "carts/carts.html", {"carts": user_cart}, request=request
        )
        response_data = {
            "message": "Количество изменено!",
            "cart_items_html": cart_items_html,
            "quantity": updated_quantity,
        }

        return JsonResponse(response_data)


class CartRemoveView(View):
    """Удаление товара из корзины"""

    def post(self, request, *args, **kwargs):
        cart_id = request.POST.get("cart_id")
        cart = Cart.objects.get(id=cart_id)
        quantity = cart.quantity
        cart.delete()

        user_cart = get_user_carts(request)
        cart_items_html = render_to_string(
            "carts/carts.html", {"carts": user_cart}, request=request
        )
        response_data = {
            "message": "Товар удален!",
            "cart_items_html": cart_items_html,
            "quantity_deleted": quantity,
        }

        return JsonResponse(response_data)

carts/templates/carts/carts.html
<div class="modal-content" id="cart-items-container">
    
    <!-- Заголовок модального окна корзины -->
    <div class="modal-header">
        <h5 class="modal-title" >
            <i class="fa-solid fa-basket-shopping"></i>&nbsp;&nbsp;Ваша корзина
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="position: absolute; right: 1rem; top: 1rem;"></button>
    </div>
   
    {# Если корзина пустая #}
    {% if not carts %}
        <div class="cart-item d-flex align-items-center" style="padding: 15px; margin: 15px;">           
            <div class="flex-grow-1 text-center" style="font-weight: 700; font-size: larger;" > 
                Ваша корзина пуста.<br>Пожалуйста добавьте товары в корзину
            </div>            
        </div>
    {% endif %}
    <!-- Тело модального окна корзины-->
    {% for cart in carts %}
        <div class="modal-body">
            <div id="cartItems">                
                <!-- Перечень товаров -->
                <div class="cart-item d-flex align-items-center">
                    <img src="{{ cart.product.image.url }}" alt="Товар" class="cart-item-img me-3">
                    <div class="flex-grow-1">
                        <h5 class="mb-1">{{cart.product.name}}</h5>
                        <p class="mb-1">
                            Цена за единицу: <span class="item-price" 
                                                data-price="{{ cart.product.sell_price }}">
                                                {{ cart.product.sell_price | floatformat:2 }}
                                            </span> ₽
                        </p>
                        <p class="mb-1">
                            Общая цена: <span class="item-total-price">{{ cart.products_price | floatformat:2 }}</span> ₽
                        </p>                                
                    <div class="small text-muted">Категория: {{cart.product.category.title}}</div>
                    </div>
                    {# Изменения кол-ва товара в крозине #}
                    <div class="d-flex align-items-center">
                        <button class="btn btn-outline-secondary btn-sm me-2 znak-products decrement" 
                                data-cart-id="{{ cart.id }}"
                                data-cart-change-url="{% url "cart:cart_change" %}">
                                {% csrf_token %}           
                            <i class="fa-solid fa-minus"></i>
                        </button>
                        <input type="text" value="{{cart.quantity}}" min="1"
                            class="form-control form-control-sm text-center fw-bold fs-6 number" 
                            style="width: 60px;" 
                            readonly>
                        <button class="btn btn-outline-secondary btn-sm ms-2 znak-products increment" 
                                data-cart-id="{{ cart.id }}"
                                data-cart-change-url="{% url "cart:cart_change" %}">
                               {% csrf_token %}
                            <i class="fa-solid fa-plus"></i>
                        </button>
                    </div>
                    {# Кнопка удаления из корзины #}
                    <a class="btn btn-danger btn-sm ms-3 cart-delete col_cart_del" 
                       data-cart-id="{{ cart.id }}"
                       href="{% url "cart:cart_remove" %}">
                        {% csrf_token %}
                        <i class="fa-solid fa-trash"></i>                         
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
    <!-- Нижняя часть модального окна -->
    <div class="modal-footer flex-column align-items-start">
        <!-- Общая информация всегда отображается -->
        <div class="w-100 mb-3">
            <p class="mb-1 fs-5">Общее количество: <span id="totalQuantity">{{carts.total_quantity}}</span></p>
            <p class="cart-total fs-5">Общая цена: <span id="totalPrice">{{carts.total_price | floatformat:2}}</span> ₽</p>
        </div>
        <hr class="hr" />
        {# Если пользователь авторизирован #}
        {% if user.is_authenticated %}
        <!-- Радиокнопки для выбора способа оплаты -->
            {% if carts %}
                {# Форма оформления заказа #}
                <form method="post" id="formCreateOrder">
                    {% csrf_token %}
                    <a class="d-none" href="{% url "orders:create_order" %}" id="formCreateOrderHref"></a>
                    {# Доступны только если в корзине есть товары #}
                    <div class="w-100 mb-3">
                        {# >>> Данные пользователя <<< #}
                        <input type="text" 
                            class="form-control d-none" 
                            id="id_username" 
                            name="username"
                            readonly 
                            value="{{user.username}}">
                        <label for="id_username" class="d-none">Имя пользователя</label>
                        <div class="row g-2">
                            <div class="col-md">
                                <div class="form-floating">
                                    <input type="text" 
                                        class="form-control" 
                                        id="id_first_name" 
                                        name="first_name"
                                        readonly 
                                        value="{{user.first_name}}">
                                    <label for="id_first_name">Ваше имя</label>
                                </div>
                            </div>
                            <div class="col-md">
                                <div class="form-floating">
                                    <input type="text"
                                        class="form-control" 
                                        id="id_last_name" 
                                        name="last_name"
                                        readonly 
                                        value="{{user.last_name}}">
                                    <label for="id_last_name">Ваша фамилия</label>
                                </div>
                            </div>
                            <div class="col-md">
                                <div class="form-floating">
                                    <input type="phone" 
                                        class="form-control" 
                                        id="id_phone_number"
                                        name="phone_number" 
                                        readonly 
                                        value="{{user.phone_number}}">
                                    <label for="id_phone_number">Ваш телефон</label>
                                </div>
                            </div>
                        </div>
                        {# Выбор способа оплаты #}
                        <br>
                        <div class="row g-2">
                            <span>Выберите способ оплаты:</span>
                            <div class="form-check mb-2">
                                <input class="form-check-input" 
                                       type="radio" 
                                       name="payment_on_get"
                                       id="id_payment_on_get" 
                                       value="0" 
                                       checked>
                                <label class="form-check-label" for="id_payment_on_get">
                                    💵 Наличными/Картой при получении
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" 
                                       type="radio" 
                                       name="payment_on_get"
                                       id="id_payment_on_get" 
                                       value="1">
                                <label class="form-check-label" for="id_payment_on_get">
                                    💳 Оплатить картой онлайн
                                </label>
                            </div>
                        </div>                    
                    </div>
                    {% endif %}
                    {% else %}
                        <!-- Блок для авторизации или регистрации -->
                        <div id="authNotice" class="w-100 text-center mb-3">
                            <p class="fs-5">Оформление заказа доступно только <strong>авторизованным</strong> пользователям.</p>
                            <a href="{% url "user:login" %}" class="btn btn-link">
                                <i class="fa-regular fa-user me-2"></i>Войти
                            </a>
                            <a href="{% url "user:register" %}" class="btn btn-link">
                                <i class="fa-solid fa-registered me-2"></i>Регистрация
                            </a>
                        </div>
                    {% endif %}
                    <hr class="hr" />
                    <!-- Кнопки "Оформить заказ" и "Закрыть" -->
                    {% if user.is_authenticated %}
                    <div class="d-flex justify-content-between w-100">                        
                        {% if carts %}
                            <hr>
                            <button type="button" class="btn btn-success" id="checkoutButtonOrder">Оформить заказ</button>
                </form>
                        {% endif %}                                        
                     {% endif %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    </div>
    </div>
</div>

carts/templates/carts/included_cart.html
{% load static %}

<div class="modal fade" id="cartModal" tabindex="-1" aria-labelledby="cartModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div id="customAlert" class="alert alert-warning alert-dismissible fade show d-none" role="alert">
            <strong>Вы удалили товар из корзины!</strong> 
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>        
        {% include "carts/carts.html" %}
    </div>
</div>