__pinocchio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from __pinocchio import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # ''' MAIN '''
    path("", include("main.urls", namespace="main")),
    # ''' Users '''
    path("user/", include("users.urls", namespace="user")),
    # ''' Carts '''
    path("cart/", include("carts.urls", namespace="cart")),
    # ''' Orers '''
    path("orders/", include("orders.urls", namespace="orders")),
    # ''' Manager '''
    path("manager/", include("manager.urls", namespace="manager")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import IndexView

app_name = 'main'

urlpatterns = [
    # ''' MAIN '''
    path("", IndexView.as_view(), name="index"),
]

manager/urls.py
from django.urls import path
from manager import views
from manager.views import (
    ManagerDashboardView,
    ProcessingOrdersView,
    ViewOrderDetailView,
    RemoveOrderView,
    EditOrderView,
    OrderQuantityChangeView,
    OrderRemoveCartView,
    AddOrderItemView,
    ConfirmOrderView,
    ConfirmsOrderListView,
    ReturnProcessingView,
)

app_name = "manager"

urlpatterns = [
    # ''' MANAGER '''
    path("", ManagerDashboardView.as_view(), name="index"),
    path(
        "processing_orders/", ProcessingOrdersView.as_view(), name="processing_orders"
    ),
    path("view_orders/<int:pk>/", ViewOrderDetailView.as_view(), name="view_orders"),
    # Удаление заказа
    path("remove_orders/", RemoveOrderView.as_view(), name="remove_orders"),
    # '''Edit-Order'''
    path("edit_order/<int:pk>/", EditOrderView.as_view(), name="edit_order"),
    path("order_quantity_change/", OrderQuantityChangeView.as_view(), name="order_quantity_change"),
    path("order_remove_cart/", OrderRemoveCartView.as_view(), name="order_remove_cart"),
    path("add_order_item/<int:order_id>/", AddOrderItemView.as_view(), name="add_order_item"),
    path("confirm_order/", ConfirmOrderView.as_view(), name="confirm_order"),
    # '''Confirms-Order'''
    path("confirms_order/", ConfirmsOrderListView.as_view(), name="confirms_order"),
    # '''Возвращаем в обработку'''
   path("return_processing/<int:order_id>/", ReturnProcessingView.as_view(), name="return_processing"),
    # '''Список наших блюд'''
    path("view_products/", views.view_products, name="view_products"),
    # '''Редактирование блюда''
    path("edit_product/<int:product_id>/", views.edit_product, name="edit_product"),
    # '''Добовление блюда в стоплист''
    path("add_to_stop_list/", views.add_to_stop_list, name="add_to_stop_list"),
    # '''Добовление нового блюда''
    path("add_product/", views.add_product, name="add_product"),
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users.views import (
    LoginView,
    RegisterView,
    LogoutView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    CheckEmailView,
    CheckUsernameView,
)

app_name = "users"

urlpatterns = [
    # Авторизация, регистрация и выход
    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    
    # Сброс пароля пользователя
    path("password_reset/", PasswordResetRequestView.as_view(), name="password_reset"),
    path(
        "password_reset_done/",
        TemplateView.as_view(template_name="users/resset/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    
    # Проверка username
    path("check_username/", CheckUsernameView.as_view(), name="check_username"),
    # Проверка уникальности email
    path("check_email/", CheckEmailView.as_view(), name="check_email"),
]

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from main.models import Products

class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ["name", "description", "image", "price", "discount", "show", "category"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Название продукта"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Описание продукта"}),
            "image": forms.FileInput(attrs={"class": "form-control-file"}),
            "price": forms.NumberInput(attrs={"class": "form-control", "step": "0.01", "placeholder": "Цена"}),
            "discount": forms.NumberInput(attrs={"class": "form-control", "step": "0.01", "placeholder": "Скидка (%)"}),
            "category": forms.Select(attrs={"class": "form-control"}),
        }

manager/views.py
from datetime import datetime
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views import View
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.http import Http404, JsonResponse
from django.db.models import Sum, Count, F
from main.models import Categories, Products
from manager.forms import ProductForm
from orders.models import Order, OrderItem

# from django.views.decorators.http import require_POST

# Группа для прав доступа к странице
def group_required(groups):
    def check_user_group(user):
        return user.groups.filter(name__in=groups).exists() or user.is_superuser

    return user_passes_test(check_user_group)


@method_decorator(group_required(["Manager"]), name="dispatch")
class ManagerDashboardView(TemplateView):
    template_name = "manager/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Total number of orders
        context["total_orders"] = Order.objects.count()

        # Total revenue from orders (sum of prices and quantities for all order items)
        context["total_revenue"] = (
            OrderItem.objects.aggregate(total=Sum(F("price") * F("quantity")))["total"]
            or 0
        )

        # Most popular product based on order item quantity
        popular_product = (
            OrderItem.objects.values("product__name")
            .annotate(total_quantity=Sum("quantity"))
            .order_by("-total_quantity")
            .first()
        )
        context["popular_product_name"] = (
            popular_product["product__name"] if popular_product else "Нет данных"
        )

        # Latest orders (e.g., 10 most recent orders)
        context["latest_orders"] = Order.objects.prefetch_related("orderitem_set").order_by(
            "-created_timestamp"
        )[:10]

        return context

# Список новых заказов
@method_decorator(group_required(["Manager"]), name="dispatch")
class ProcessingOrdersView(ListView):
    model = Order
    template_name = "manager/processing_orders.html"
    context_object_name = "orders"

    def get_queryset(self):
        # Filter orders with the status "В обработке"
        return Order.objects.filter(status="В обработке")

    def get_context_data(self, **kwargs):
        # Add additional context for the count of orders
        context = super().get_context_data(**kwargs)
        context["count_order"] = self.get_queryset().count()
        return context


# Просмотр информации по заказу
@method_decorator(group_required(["Manager"]), name="dispatch")
class ViewOrderDetailView(DetailView):
    model = Order
    template_name = "manager/view_order.html"
    context_object_name = "order"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get related order items
        order_items = OrderItem.objects.filter(order=self.object)

        # Calculate total price and total quantity
        total_price = sum(item.price * item.quantity for item in order_items)
        total_quantity = sum(item.quantity for item in order_items)

        # Determine payment status
        if self.object.payment_on_get:
            status_payment = "Оплата после получения"
        elif self.object.is_paid:
            status_payment = "Заказ оплачен картой"
        else:
            status_payment = "Не оплачено"

        # Add custom context
        context["order_items"] = order_items
        context["total_price"] = total_price
        context["total_quantity"] = total_quantity
        context["status_payment"] = status_payment

        return context


# Удаление существующего заказа
@method_decorator(group_required(["Manager"]), name="dispatch")
class RemoveOrderView(View):
    def post(self, request, *args, **kwargs):
        # Get `order_id` from the request POST data
        order_id = request.POST.get("order_id")

        if not order_id:
            return JsonResponse({"error": "ID заказа не передан."}, status=400)

        # Find the order or return a 404 error
        order = get_object_or_404(Order, id=order_id)
        order.delete()  # Delete the order

        return JsonResponse({"message": "Заказ успешно удалён."})

    def get(self, request, *args, **kwargs):
        return JsonResponse(
            {"error": "Удаление доступно только через POST-запрос."}, status=405
        )


# ''' Редактирование заказа пользователя '''
@method_decorator(group_required(["Manager"]), name="dispatch")
class EditOrderView(DetailView):
    model = Order
    template_name = "manager/edit_order.html"
    context_object_name = "order"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get related order items
        order_items = OrderItem.objects.filter(order=self.object)

        # Calculate total price and total quantity
        total_price = sum(item.price * item.quantity for item in order_items)
        total_quantity = sum(item.quantity for item in order_items)

        # List of all products for modal selection
        products = Products.objects.all()

        # Prepare context data
        context["order_items"] = order_items
        context["total_price"] = total_price
        context["total_quantity"] = total_quantity
        context["products"] = products
        context["added_product_ids"] = [item.product.id for item in order_items]

        return context


# Изменение кол-ва блюд в заказе
@method_decorator(group_required(["Manager"]), name="dispatch")
class OrderQuantityChangeView(View):
    def post(self, request, *args, **kwargs):
        # Get order item ID and new quantity from POST data
        order_id = request.POST.get("order_id")
        quantity = request.POST.get("quantity")

        if not order_id or not quantity:
            return JsonResponse({"error": "order_id и quantity обязательны."}, status=400)

        # Get the specific order item or return 404 if not found
        order_item = get_object_or_404(OrderItem, id=order_id)

        # Update the quantity
        try:
            order_item.quantity = int(quantity)
            order_item.save()
        except ValueError:
            return JsonResponse({"error": "Количество должно быть числом."}, status=400)

        return JsonResponse({"success": True})

# Удаление блюда из заказа пользлвателя
@method_decorator(group_required(["Manager"]), name="dispatch")
class OrderRemoveCartView(View):
    def post(self, request, *args, **kwargs):
        # Get order item ID from POST data
        order_id = request.POST.get("order_id")

        if not order_id:
            return JsonResponse({"error": "ID заказа не передан."}, status=400)

        # Get the order item or return 404
        order_item = get_object_or_404(OrderItem, id=order_id)

        # Delete the order item
        order_item.delete()

        return JsonResponse({"success": True})

    def get(self, request, *args, **kwargs):
        return JsonResponse(
            {"error": "Удаление доступно только через POST-запрос."}, status=405
        )


# Добавление нового товара в заказ пользователя
@method_decorator(group_required(["Manager"]), name="dispatch")
class AddOrderItemView(View):
    def post(self, request, order_id, *args, **kwargs):
        # Retrieve the order using `order_id`
        order = get_object_or_404(Order, pk=order_id)

        # Get product_id and quantity from POST data
        product_id = request.POST.get("product_id")
        quantity = request.POST.get("quantity")

        if not product_id or not quantity:
            # If either value is missing, return an error
            return JsonResponse({"error": "Продукт или количество не переданы."}, status=400)

        try:
            quantity = int(quantity)  # Ensure quantity is a valid integer
        except ValueError:
            return JsonResponse({"error": "Количество должно быть числом."}, status=400)

        # Find the product or return 404 if not found
        product = get_object_or_404(Products, pk=product_id)

        # Create a new order item
        OrderItem.objects.create(
            order=order,
            product=product,
            quantity=quantity,
            name=product.name,  # Save the product's name
            price=product.price,  # Save the product's price
        )

        # Redirect back to the referring page
        return redirect(request.META.get("HTTP_REFERER", "/"))


# Подтверждаем заказ пользователя
@method_decorator(group_required(["Manager"]), name="dispatch")
class ConfirmOrderView(View):
    def post(self, request, *args, **kwargs):
        # Retrieve data from POST request
        order_id = request.POST.get("order_id")
        order_date = request.POST.get("dateOrder")

        # Check if order_date is provided
        if not order_date:
            raise Http404("Страница не найдена")

        # Convert date string to datetime object
        try:
            order_date_obj = datetime.strptime(order_date, "%Y-%m-%dT%H:%M")  # datetime-local format
        except ValueError:
            raise Http404("Страница не найдена")

        # Retrieve the order by ID or raise 404
        order = get_object_or_404(Order, id=order_id)

        # Update order fields
        order.order_date = order_date_obj
        order.status = "Подтвержден"
        order.save()  # Save changes

        # Redirect to processing orders page
        return redirect("manager:processing_orders")

    def get(self, request, *args, **kwargs):
        raise Http404("Страница не найдена")


# Список подтвержденных заказов
@method_decorator(group_required(["Chefs", "Manager"]), name="dispatch")
class ConfirmsOrderListView(ListView):
    model = Order
    template_name = "manager/confirms_order.html"

manager/templates/manager/includes/header.html
{% load static %}
<header id="page-topbar">
    <div class="navbar-header">
        <!-- LOGO -->
        <div class="navbar-brand-box d-flex align-items-left">
            <a href="{% url "manager:index" %}" class="logo">
                <i class="mdi mdi-account-star-outline"></i>
                <span>
                    Панель менеджера
                </span>
            </a>

            <button type="button" class="btn btn-sm mr-2 font-size-16 d-lg-none header-item waves-effect waves-light" data-toggle="collapse" data-target="#topnav-menu-content">
                <i class="fa fa-fw fa-bars"></i>
            </button>
        </div>
        
        <div class="d-flex align-items-center">
            <div class="form-group m-0">
                <div class="input-group">
                    <div class="input-group-append">
                        <ul class="nav nav-pills nav-fill">
                            <li class="nav-item">
                              <a class="nav-link active" target="_blank" href="{% url "main:index" %}">Перейти на сайт</a>
                            </li>
                        </ul>                        
                    </div>
                </div>
            </div>        
            <div class="dropdown d-inline-block ml-2">
                <button type="button" class="btn header-item waves-effect waves-light" id="page-header-user-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="{% static "manager/images/Avatar.png" %}"
                        alt="Avatar">
                    <span class="d-none d-sm-inline-block ml-1">{{request.user.username}}</span>
                    <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item d-flex align-items-center justify-content-between" href="{% url "user:logout" %}">
                        <span>Завершить сеанс</span>
                    </a>
                </div>
            </div>            
        </div>
    </div>
</header>

manager/templates/manager/includes/nav.html
{% load static %}
{% load count_orders_tags %}

{% get_Count_Orders as count_order %}
{% get_Count_Orders_Confirm as count_confirm %}


{# Навигация на сайте #}
<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">
            
            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">
                    {# Главная страницы сайта со статистикой #}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "manager:index" %}">
                            <i class="mdi mdi-view-dashboard mr-2"></i>Статистика
                        </a>
                    </li>
                    {# Список заказов #}                
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-components" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-table-border mr-2"></i>Заказы <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="topnav-components">
                            <a href="{% url "manager:processing_orders" %}" class="dropdown-item">
                                Новые заказы
                                <span class="badge badge-info badge-pill ml-4" style="font-size:12px;">
                                    {{count_order}}
                                </span>
                            </a>
                            <a href="{% url "manager:confirms_order" %}" class="dropdown-item">
                                Подтвержденные
                                <span class="badge badge-success badge-pill ml-4" style="font-size:12px;">
                                    {{count_confirm}}
                                </span>
                            </a>
                            <a href="ui-carousel.html" class="dropdown-item">Завершенные</a>
                        </div>
                    </li>
                    {# Список наших блюд #}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-components" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-pizza mr-2"></i>Наша продукция <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="topnav-components">
                            <a href="{% url "manager:view_products" %}" class="dropdown-item">
                                Список блюд                              
                            </a>
                            <a href="{% url "manager:confirms_order" %}" class="dropdown-item">
                                Стоп-лист
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>