__pinocchio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from __pinocchio import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # ''' MAIN '''
    path("", include("main.urls", namespace="main")),
    # ''' Users '''
    path("user/", include("users.urls", namespace="user")),
    # ''' Carts '''
    path("cart/", include("carts.urls", namespace="cart")),
    # ''' Orers '''
    path("orders/", include("orders.urls", namespace="orders")),
    # ''' Manager '''
    path("manager/", include("manager.urls", namespace="manager")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import IndexView

app_name = 'main'

urlpatterns = [
    # ''' MAIN '''
    path("", IndexView.as_view(), name="index"),
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users.views import (
    LoginView,
    RegisterView,
    LogoutView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    CheckEmailView,
    CheckUsernameView,
)

app_name = "users"

urlpatterns = [
    # Авторизация, регистрация и выход
    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    
    # Сброс пароля пользователя
    path("password_reset/", PasswordResetRequestView.as_view(), name="password_reset"),
    path(
        "password_reset_done/",
        TemplateView.as_view(template_name="users/resset/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    
    # Проверка username
    path("check_username/", CheckUsernameView.as_view(), name="check_username"),
    # Проверка уникальности email
    path("check_email/", CheckEmailView.as_view(), name="check_email"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator


# Create your models here.
class User(AbstractUser):
    phone_number = models.CharField(
        max_length=20,  # Adjust based on your needs
        validators=[
            RegexValidator(
                regex=r"^\+7\s\(\d{3}\)\s\d{3}-\d{2}-\d{2}$",  # Example regex for international phone numbers
                message="Номер телефона должен быть в формате: '+7 (***) ***-**-**'.",
            )
        ],
        verbose_name="Номер телефона",
        blank=False,
        null=False,
    )

    class Meta:
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return str(self.pk) + " - " + self.username

users/forms.py
from pyexpat import model
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm
from django.forms import fields

from users.models import User


# Форма авторизации ===>
class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                "class": "form-control form-control-lg",
                "placeholder": "Имя пользователя",
                "required": True,
                "autocomplete": "off",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": "form-control form-control-lg",
                "placeholder": "Ваш пароль",
                "required": True,
                "autocomplete": "off",
            }
        ),
    )

    class Meta:
        model = User
        fields = ["username", "password"]


# Форма для регистрации пользователя
class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "password1",
            "password2",
        )

    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    phone_number = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

# Форма для восстановления пароля пользователя
class PasswordResetRequestForm(PasswordResetForm):
    
    class Meta:
        model = User
        fields = (            
            "email",            
        )  

    email = forms.EmailField(max_length=100)    

users/views.py
from django.views import View
from django.views.generic import FormView, TemplateView
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.http import urlsafe_base64_decode
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.forms import SetPasswordForm
from django.shortcuts import redirect, render
from django.core.mail import send_mail
from django.utils.encoding import force_str
from django.urls import reverse
from django.contrib.auth.tokens import default_token_generator
from carts.models import Cart
from users.models import User
from users.forms import PasswordResetRequestForm, UserLoginForm, UserRegistrationForm

class LoginView(FormView):
    template_name = "users/login.html"
    form_class = UserLoginForm

    def form_valid(self, form):
        username = self.request.POST["username"]
        password = self.request.POST["password"]
        user = authenticate(username=username, password=password)
        session_key = self.request.session.session_key

        if user:
            auth_login(self.request, user)
            # Обновляем корзину для авторизованного пользователя
            if session_key:
                Cart.objects.filter(session_key=session_key).update(
                    user=user, session_key=None
                )
            # Перенаправляем на предыдущую страницу или главную
            next_url = self.request.GET.get("next")
            return HttpResponseRedirect(next_url or reverse("main:index"))

        return super().form_invalid(form)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse("main:index"))
        return super().get(request, *args, **kwargs)


class RegisterView(FormView):
    template_name = "users/register.html"
    form_class = UserRegistrationForm

    def form_valid(self, form):
        form.save()
        session_key = self.request.session.session_key
        user = form.instance
        auth_login(self.request, user)
        # Обновляем корзину
        if session_key:
            Cart.objects.filter(session_key=session_key).update(user=user)
        return HttpResponseRedirect(reverse("main:index"))


class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return redirect(reverse("main:index"))



class PasswordResetRequestView(FormView):
    template_name = "users/resset/password_reset.html"
    form_class = PasswordResetRequestForm

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        try:
            user = User.objects.get(email=email)
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            protocol = "https" if self.request.is_secure() else "http"
            domain = self.request.get_host()
            reset_url = reverse(
                "user:password_reset_confirm", kwargs={"uidb64": uid, "token": token}
            )
            full_url = f"{protocol}://{domain}{reset_url}"

            mail_subject = "Сброс пароля"
            message = render_to_string(
                "users/resset/password_reset_email.html",
                {
                    "user": user,
                    "protocol": protocol,
                    "domain": domain,
                    "uid": uid,
                    "token": token,
                    "reset_url": full_url,
                },
            )
            send_mail(
                mail_subject,
                message,
                "meetnight1027@yandex.ru",
                [email],
                fail_silently=False,
            )
            return redirect("user:password_reset_done")
        except User.DoesNotExist:
            form.add_error("email", "Пользователь с таким email не найден.")
            return super().form_invalid(form)


class PasswordResetConfirmView(View):
    template_name = "users/resset/password_reset_confirm.html"

    def post(self, request, uidb64=None, token=None, *args, **kwargs):
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = get_object_or_404(User, pk=uid)

        if default_token_generator.check_token(user, token):
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                return redirect("user:password_reset_complete")
            return render(request, self.template_name, {"form": form})

    def get(self, request, uidb64=None, token=None, *args, **kwargs):
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = get_object_or_404(User, pk=uid)

        if default_token_generator.check_token(user, token):
            form = SetPasswordForm(user)
            return render(request, self.template_name, {"form": form})
        else:
            return render(request, "users/resset/password_reset_invalid.html")


class PasswordResetCompleteView(TemplateView):
    template_name = "users/resset/password_reset_complete.html"


class CheckEmailView(View):
    """Проверка уникальности email"""

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email", "")
        is_unique = not User.objects.filter(
            email=email
        ).exists()  # Проверяем, уникален ли email
        return JsonResponse({"is_unique": is_unique})

    def get(self, request, *args, **kwargs):
        return JsonResponse({"error": "Invalid request"}, status=400)


class CheckUsernameView(View):
    """Проверка уникальности username"""

    def post(self, request, *args, **kwargs):
        username = request.POST.get("username", "")
        is_unique = not User.objects.filter(username=username).exists()
        return JsonResponse({"is_unique": is_unique})

    def get(self, request, *args, **kwargs):
        return JsonResponse({"error": "Invalid request"}, status=400)

users/templates/users/login.html
{% extends "user_base.html" %}
{% load static %}
{% block Title %} Авторизация пользователя {% endblock %}

{# *** Авторизация пользователя на сайте *** #}
{% block login-content %}
    <div class="bg-fon"></div>  
    <section class="vh-100">        
        <div class="container py-5 h-100">
            <img src="{% static "img/logo3.png" %}" class="logo_auth_mobile" alt="logo">
        <div class="row d-flex justify-content-center align-items-center h-100">            
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="{% static "img/auth.jpg" %}"
                            alt="login form" class="img-fluid bg-login image-login" style="border-radius: 1rem 0 0 1rem;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center ">
                            <div class="card-body p-4 p-lg-5 text-black">
                                <form action="{% url "user:login" %}" method="post">
                                    {% csrf_token %}
                                    {% comment %} {{form.as_p}}  {% endcomment %}
                                    <div class="d-flex align-items-center mb-3 pb-1">
                                        <i class="fa fa-sign-out fa-2x me-3" style="color: #ff6219;" aria-hidden="true"></i>
                                        <span class="h1 fw-bold mb-0">Авторизация</span>
                                    </div>
                
                                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Войдите в свою учетную запись</h5>
                                    {# Проверка на ошибки #}
                                    {% if form.non_field_errors %}
                                        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                                            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                                            </symbol>
                                            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                                            </symbol>
                                            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                            </symbol>
                                        </svg>
                                        <div class="alert alert-danger d-flex align-items-center" role="alert">
                                            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                                            <div>
                                                {{form.non_field_errors}}
                                            </div>
                                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                        </div>                                
                                    {% endif %}
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <input type="text" 
                                                name="username" 
                                                class="form-control form-control-lg" 
                                                placeholder="Имя пользователя" 
                                                autocomplete="off" 
                                                maxlength="150" 
                                                id="id_username"
                                                value="{% if form.username.value %}{{form.username.value}}{% endif %}" 
                                                autofocus required/>
                                        <label class="form-label" for="id_username">Логин</label>
                                    </div>
                
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <input type="password" 
                                                name="password" 
                                                autocomplete="off" 
                                                class="form-control form-control-lg" 
                                                placeholder="Ваш пароль" 
                                                required 
                                                id="id_password">
                                        <label class="form-label" for="id_password">Пароль</label>
                                    </div>   
                                    <div class="pt-1 mb-4">
                                        <button data-mdb-button-init data-mdb-ripple-init class="btn btn-dark btn-lg btn-block" id="user_login" type="submit">&nbsp;Вход&nbsp;</button>
                                    </div>
                                    <a class="small text-muted" href="{% url "user:password_reset" %}">Забыли пароль?</a>
                                    <p class="mb-5 pb-lg-2" style="color:rgb(2, 28, 31);">У Вас нет аккаунта? 
                                        <a href="{% url "user:register" %}" style="color: #393f81;">Регистрация</a>
                                    </p>
                                    <p>
                                        <a href=" {% url "main:index" %} " >
                                            <i class="fa-solid fa-backward"></i> &nbsp;&nbsp;
                                            Вернуться на главную
                                        </a>
                                    </p>                            
                                </form>        
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
{% endblock login-content %}

users/templates/users/register.html
{% extends "user_base.html" %}
{% load static %}

{% block Title %} Регистрация пользователя {% endblock %}
{% block mbb-css %}
    <link rel="stylesheet" type="text/css" href="{% static "css/mdb/mdb.min.css" %}">
{% endblock mbb-css %}
{% block mbd-js %}
    <script src="{% static "js/mdb/mdb.umd.min.js" %}"></script>
{% endblock mbd-js %}
{#=== Block Validate Scripts ===#}
{% block validate-scripts %}
    <script src="{% static "validate/jquery-3.6.0.min.js" %}"></script>   
    <script src="{% static "validate/jquery.validate.min.js" %}"></script>   
    <script src="{% static "validate/my.script.validate.js" %}"></script>   
    <script src="{% static "validate/jquery.maskedinput.min.js" %}"></script>  
{% endblock validate-scripts %}
{#=== Ввод номера телефона ===#}
{% block phone_script %}
    <script>
        $("#id_phone_number").click(function(){
            $(this).setCursorPosition(3);
        }).mask("+7 (999) 999-99-99");
    </script>
{% endblock  %}
{#=== Блок формы регистрации ===#}
{% block Register %}

    <div class="bg-fon"></div> 
    <section class="vh-100 gradient-custom">
        <img src="{% static 'img/logo3.png' %}" class="logo_register_mobile" alt="logo">
        <div class="container py-5 h-100">
            <div class="row justify-content-center align-items-center h-100">
                <div class="col-12 col-lg-9 col-xl-7">
                    <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                        <div class="card-body p-4 p-md-5">
                            <p>
                                <span class="text-secondary">Всполнили пароль?</span>
                                <a href=" {% url "user:login" %} " class="text-success" >
                                    <i class="fa-solid fa-backward"></i> &nbsp;&nbsp;
                                    Авторизация
                                </a>
                            </p>
                            <h2 class="mb-4 pb-2 pb-md-0 mb-md-5">Форма регистрации</h2>
                            
                            <form id="registrationForm" action="{% url "user:register" %}" method="post">
                                {% csrf_token %}
                                    {# === Вводим логин === #}
                                <div class="row mb-3">
                                    <label class="col-sm-3 col-form-label" for="id_username">Ваш логин <i class="red-star">*</i></label>
                                    <div class="col-sm-9">
                                        <input type="text" 
                                               id="id_username" 
                                               class="form-control form-control-lg"
                                               value="{% if form.username.value %} {{form.username.value}} {% endif %}"
                                               name="username"
                                               required
                                               placeholder="Ваш Логин"/>
                                    </div>
                                </div>
                                {# === Вводим имя === #}
                                <div class="row mb-3">
                                    <label class="col-sm-3 col-form-label" for="id_first_name">Ваше имя <i class="red-star">*</i></label>
                                    <div class="col-sm-9">
                                        <input type="text" 
                                                id="id_first_name" 
                                                class="form-control form-control-lg"
                                                value="{% if form.first_name.value %} {{form.first_name.value}} {% endif %}" 
                                                name="first_name"
                                                placeholder="Имя"/>
                                    </div>
                                </div>
                                {# === Вводим фамилию === #}
                                <div class="row mb-3">
                                    <label class="col-sm-3 col-form-label" for="id_last_name">Ваша Фамилия <i class="red-star">*</i></label>
                                    <div class="col-sm-9">
                                        <input type="text" 
                                                id="id_last_name" 
                                                class="form-control form-control-lg"
                                                value="{% if form.last_name.value %} {{form.last_name.value}} {% endif %}" 
                                                name="last_name"
                                                placeholder="Фамилия"/>
                                    </div>
                                </div>
                                {# === Вводим Email adress === #}
                                <div class="row mb-3">
                                    <label for="id_email" class="col-sm-3 col-form-label">Ваш Email <i class="red-star">*</i></label>
                                    <div class="col-sm-9">
                                        <input type="email" 
                                                id="id_email" 
                                                class="form-control form-control-lg"
                                                value="{% if form.email.value %} {{form.email.value}} {% endif %}" 
                                                name="email"
                                                required
                                                placeholder="Email"/>
                                    </div>
                                </div>
                                {# === Вводим Телефон === #}
                                <div class="row mb-3">
                                    <label for="id_phone_number" class="col-sm-3 col-form-label">Ваш телефон <i class="red-star">*</i></label>
                                    <div class="col-sm-9">
                                        <input type="tel" 
                                                id="id_phone_number" 
                                                class="form-control form-control-lg"
                                                value="{% if form.phone_number.value %} {{form.phone_number.value}} {% endif %}" 
                                                name="phone_number"
                                                required
                                                placeholder="+7 (___) ___-__-__"/>
                                    </div>
                                </div>
                                {# === Вводим Пароль - 1 === #}
                                <div class="row mb-3">
                                    <label for="id_password1" class="col-sm-3 col-form-label">Ваш пароль <i class="red-star">*</i></label>
                                    <div class="col-sm-9">
                                        <input type="password" 
                                                id="id_password1" 
                                                class="form-control form-control-lg" 
                                                value="{% if form.password1.value %} {{form.password1.value}} {% endif %}"
                                                name="password1"
                                                required
                                                placeholder="Ваш пароль"/>
                                    </div>
                                </div>
                                {# === Вводим Пароль - 2 === #}
                                <div class="row mb-3">
                                    <label for="id_password2" class="col-sm-3 col-form-label">Повтор пароля <i class="red-star">*</i></label>
                                    <div class="col-sm-9">
                                        <input type="password" 
                                                id="id_password2" 
                                                class="form-control form-control-lg"
                                                value="{% if form.password2.value %} {{form.password2.value}} {% endif %}" 
                                                name="password2"
                                                required
                                                placeholder="Повторите пароль"/>
                                    </div>
                                </div>
                                {# === Кнопка отправки формы и сброса формы === #}								
                                <div class="row">
                                    <label class="col-sm-3 col-form-label"></label>
                                    <div class="col-sm-9">
                                        <div class="d-md-flex d-grid align-items-center gap-3">
                                            <button type="submit" class="btn btn-primary px-4" name="submit2">Регистрация</button>
                                            <button type="reset" class="btn btn-light px-4">Сброс формы</button>
                                        </div>
                                    </div>
                                </div>
							</form>
                            <p>
                                <br>
                                <a href=" {% url "main:index" %} " >
                                    <i class="fa-solid fa-backward"></i> &nbsp;&nbsp;
                                    Вернуться на главную
                                </a>
                            </p>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
    